openapi: 3.1.0
info:
  title: API для проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

tags:
  - name: offers
    description: Действия с объявлениями.
  - name: users
    description: Действия с пользователем.
  - name: comments
    description: Действия с комментариями.

paths:

  /offers/new:
    post:
      tags:
        - offers
      summary: Создать новое предложение.
      security:
        - bearerAuth: []
      description: Создать новое предложение. Только для авторизованных пользователей
      requestBody:
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/offerNew'
        required: true
      responses:
        "201":
          description: Предложение создано.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "400":
          description: Данные некоректны.
        "401":
          description: Создавать прдложения могут только авторизованные пользователи.

  /offers:
    get:
      tags:
        - offers
      summary: Загрузить список предложений
      description: Возвращает массив предложений.
      responses:
        "200":
          description: Информация для отображения списка предложений.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'

  /offers/{offerId}:
    get:
      tags:
        - offers
      summary: Загрузить информацию о предложении.
      description: Детальная информация с offerId.
      responses:
        "200":
          description: Подробная информация о предложении.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerDetails'
        "404":
          description: Предложения с таким идентификатором не существует.

    patch:
      tags:
        - offers
      summary: Редактировать предложение
      security:
        - bearerAuth: []
      description: Изменяет данные предложения с offerId.
      requestBody:
        description: Измененная информация о предложении.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/offer'
        required: true
      responses:
        "200":
          description: Возвращает информацию о предложении с изменениями.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "400":
          description: Данные некоректны.
        "401":
          description: Редактировать предложения могут только авторизованные пользователи.

    delete:
      tags:
        - offers
      summary: Удалить данные о предложении с идентификатором offerId.
      security:
        - bearerAuth: []
      description: Удаляет данные о предложении с идентификатором offerId.
      requestBody:
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/offerDelete'
        required: true
      responses:
        "200":
          description: Предложение удалено.
        "401":
          description: Удалять предложения могут только авторизованные пользователи.
        "404":
          description: Предложения с таким идентификатором не существует.

  /offers/premium:
    get:
      tags:
        - offers
      summary: Получить список премиальных предложений для определённого города.
      description: Возвращает список премиальных предложений для определённого города.
      responses:
        "200":
          description: Информация для отображения списка премиальных предложений.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'

  /offers/favorites:
    get:
      tags:
        - offers
      summary: Получить список избранных предложений.
      security:
        - bearerAuth: []
      description: Возвращает массив предложений, добавленных в избранное.
      responses:
        "200":
          description: Информация для отображения списка избранных предложений. Предложения с флагом «isFavorite»
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'
        "401":
          description: Избранные предложения доступны только авторизованным пользователям.

  /offers/favorites/{offerId}/{status}:
    get:
      tags:
        - offers
      summary: Изменить статус избранного у предложения.
      security:
        - bearerAuth: []
      description: Возвращает предложение с идентификатором offerId с актуальным состоянием поля isFavorite.
      responses:
        "200":
          description: Cостояние поля isFavorite изменено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerDetails'
        "401":
          description: Менять статус поля isFavorite могут только авторизованные пользователи.

  /comments/{offerId}:
    get:
      tags:
        - comments
      summary: Загрузить список комментариев для предложения с идентификатором offerId.
      description: Возвращает список комментариев для предложения с идентификатором offerId.
      responses:
        "200":
          description: Информация для отображения списка комментариев для прелдожения с идентификатором offerId.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'
        "404":
          description: Невозможно загрузить комментарии. Предложения с таким идентификатором не существует.

    post:
      tags:
        - comments
      summary: Добавить новый комментарий для предложения с идентификатором offerId.
      security:
        - bearerAuth: []
      description: Сохраняет новый комментарий для предложения с идентификатором offerId.
      requestBody:
        description: Информация для создания нового комментария.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comment'
        required: true
      responses:
        "200":
          description: Комментарий добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        "400":
          description: Введенные данные некоректны.
        "401":
          description: Добавлять новые комментарии могут только авторизованные пользователи.

  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Сохраняет данные нового пользователя.
      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        "201":
          description: Данные нового пользователя сохранены. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: Введенные данные некоректны.
        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизовать пользователя на основе логина и пароля.
      description: Выдает пользователю токен. Пользователь получает статус `авторизован`.
      requestBody:
        description: Информация для авторизации пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userLogin'
        required: true
      responses:
        "200":
          description: Пользователь успешно авторизован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: Неверный логин и/или пароль.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userError'

    get:
      tags:
        - users
      summary: Проверить статус авторизации пользователя
      security:
        - bearerAuth: []
      description: Возвращает информацию о статусе авторизации пользователя.
      responses:
        "200":
          description: Пользователь авторизован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: Неверный логин и/или пароль.

  /users/logout:
    delete:
      tags:
        - users
      summary: Завершить сеанс пользователя, выйти из закрытой части приложения.
      description: Удаляет выданный пользователю токен. Пользователь получает статус `не авторизован`.
      responses:
        "204":
          description: Выданный пользователю токен удален. Пользователь не авторизован.

components:

  schemas:

    offerNew:
      type: object
      properties:
        title:
          type: string
          example: 'Уютная квартира в центре Парижа'
        description:
          type: string
          example: 'Прекрасная квартира с видом на Эйфелеву башню и исторический центр города.'
        postDate:
          type: string
          example: '2024-02-19T08:45:40.283Z'
        city:
          type: string
          example: Paris
        previewPhoto:
          type: string
          example: preview-photo-a.jpg
        photos:
          type: string[]
          example: [photo-1.jpg, photo-2.jpg, photo-3.jpg, photo-4.jpg, photo-5.jpg, photo-6.jpg]
        isPremium:
          type: boolean
          example: true
        isFavorite:
          type: boolean
          example: false
        rating:
          type: number
          example: 4
        type:
          type: string
          example: apartment
        roomCount:
          type: number
          example: 2
        guestsCount:
          type: number
          example: 4
        price:
          type: number
          example: 5000
        facilities:
          type: string[]
          example: [Laptop friendly workspace, Fridge]
        author:
          type: string
          example: 661bef9f1bdfe1195539b653
        coordinates:
          type: string
          example: 'latitude: 48.85661, longitude: 2.351499'

    offerDetails:
      type: object
      properties:
        allOf:
          $ref: '#/components/schemas/offerNew'
        id:
          type: string
          example: 661bef9f1bdfe1195539b655

    offerDelete:
      type: object
      properties:
        id:
          type: string
          example: 661bef9f1bdfe1195539b655

    offer:
      type: object
      properties:
        title:
          type: string
          example: 'Небольшая квартира в спальном районе'
        description:
          type: string
          example: 'Уютная квартира в тихом районе города.'
        postDate:
          type: string
          example: '2024-02-19T08:45:40.283Z'
        city:
          type: string
          example: Paris
        previewPhoto:
          type: string
          example: prev-photo-a.jpg
        photos:
          type: string[]
          example: [photo-1.jpg, photo-2.jpg, photo-3.jpg, photo-4.jpg, photo-5.jpg, photo-6.jpg]
        isPremium:
          type: boolean
          example: true
        isFavorite:
          type: boolean
          example: false
        rating:
          type: number
          example: 4
        type:
          type: string
          example: apartment
        roomCount:
          type: number
          example: 2
        guestsCount:
          type: number
          example: 4
        price:
          type: number
          example: 5000
        facilities:
          type: string[]
          example: [Laptop friendly workspace, Fridge]
        author:
          type: string
          example: 661bef9f1bdfe1195539b653
        coordinates:
          type: string
          example: 'latitude: 48.85661, longitude: 2.351499'

    user:
      type: object
      properties:
        name:
          type: string
          example: Keks
        email:
          type: string
          example: example@example.ru
        avatarPath:
          type: string
          example: https://avatars/example.jpg
        password:
          type: string
          example: 4a83854cf6f0112b4295bddd535a9b3fbe54a3f90e853b59d42e4bed553c55a4
        userKind:
          type: string
          example: pro

    userCreated:
      type: object
      properties:
        id:
          type: string
          example: 661bef9f1bdfe1195539b653
        email:
          type: string
          example: example@example.ru

    userLogin:
      type: object
      properties:
        email:
          type: string
          example: example@example.ru
        passord:
          type: string
          example: 4a83854cf6f0112b4295bddd535a9b3fbe54a3f90e853b59d42e4bed553c55a4

    userError:
      type: object
      properties:
        errorType:
          type: string
          example: Validation error
        message:
          type: string
          example: Ошибка введенных данных. Проверьте правильность логина и пароля

    comment:
      type: object
      properties:
        text:
          type: string
          example: Прекрасные апартаменты
        postDate:
          type: string
          example: 2024-02-19T08:45:40.283Z
        rating:
          type: number
          example: 4
        author:
          type: string
          example: 661bef9f1bdfe1195539b658

    commentsList:
      type: object
      properties:
        allOf:
          $ref: '#/components/schemas/comment'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
